# -*- coding: utf-8 -*-
"""MINIPROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IgcDfWy2soF9bEqaXdfneS1aLjAJYzO6
"""

import numpy as np
import pandas as pd
import joblib
from tensorflow.keras.models import load_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix



import streamlit as st

st.set_page_config(
    page_title="DeepBF Malicious URL Detection",
    layout="wide"
)

st.title("DeepBF: Malicious URL Detection")
st.write("Bloom Filter + evoCNN based malicious URL detection system")

from google.colab import drive
drive.mount('/content/drive')


MODEL_PATH = "/content/drive/MyDrive/mini_project/ga_evocnn_best_model.h5"
SCALER_PATH = "/content/drive/MyDrive/mini_project/minmax_scaler.pkl"

model = load_model(MODEL_PATH)
scaler = joblib.load(SCALER_PATH)

print("Model and scaler loaded successfully")

file="dataset.csv"
data = pd.read_csv(file)
data = data.fillna(0)
X = data.iloc[:, :-1]
y = data.iloc[:, -1]
X = X.values
X_padded = np.pad(X, ((0,0),(0,2)), mode='constant')
X_df = pd.DataFrame(X_padded)
X_df['label'] = y.values
new_name = file.replace(".csv", "_preprocessed.csv")
X_df.to_csv(new_name, index=False)
print(f"Saved: {new_name}")

datasets = [ "dataset_preprocessed.csv"]
for file in datasets:
    data = pd.read_csv(file)
    data.iloc[:, -1] = data.iloc[:, -1].apply(
        lambda x: 0 if str(x).lower() == "benign" else 1
    )
    data.to_csv(file, index=False)
print("datasets encoded.")

"""Modified MurMur Hash Function"""

def mmurmur(url: str, seed: int = 0) -> int:
    data = url.encode('utf-8')
    length = len(data)
    h = seed ^ length
    for c in data:
        k = c & 0xFF
        k = ((k << 13) | (k >> 19)) & 0xFFFFFFFF
        k ^= (k << 7) & 0xFFFFFFFF
        k = ((k << 5) | (k >> 27)) & 0xFFFFFFFF

        h ^= k
        h = ((h << 11) | (h >> 21)) & 0xFFFFFFFF
        h ^= (h << 3) & 0xFFFFFFFF
    h ^= length
    h ^= (h >> 16)
    h = ((h << 13) | (h >> 19)) & 0xFFFFFFFF
    h ^= (h >> 13)
    return h & 0xFFFFFFFF

class BloomFilter2D:
    def __init__(self, M: int, N: int):
        self.M = M
        self.N = N
        self.beta = 61
        self.filter = np.zeros((M, N), dtype=np.uint64)

    def _get_positions(self, url: str):
        positions = []
        for seed in range(5):
            h = mmurmur(url, seed)
            i = h % self.M
            j = h % self.N
            rho = h % self.beta
            positions.append((i, j, rho))
        return positions

    def insert(self, url: str):
        for i, j, rho in self._get_positions(url):
            self.filter[i, j] |= (np.uint64(1) << rho)

    def lookup(self, url: str) -> bool:
        for i, j, rho in self._get_positions(url):
            bit = (self.filter[i, j] & (np.uint64(1) << rho)) >> rho
            if bit == 0:
                return False
        return True

def clean_feature_vector(features):
    features = np.array(features, dtype=np.float32).flatten()
    features = np.nan_to_num(features, nan=0.0, posinf=1e6, neginf=-1e6)
    features = np.clip(features, -1e6, 1e6)
    return features


def vector_to_string(features):
    features = clean_feature_vector(features)
    return "_".join(map(str, features.astype(int)))

def prepare_features_for_cnn(features, scaler):
    features = clean_feature_vector(features)

    if len(features) == 79:
        features = np.pad(features, (0, 2), mode='constant')
    elif len(features) != 81:
        raise ValueError(f"Expected 79 or 81 features, got {len(features)}")

    features_scaled = scaler.transform(features.reshape(1, -1)).astype(np.float32)
    features_scaled = features_scaled.reshape(1, 9, 9, 1)

    return features_scaled

@st.cache_resource
def create_filters():
  M = 10007
  N = 10009
  malicious_filter = BloomFilter2D(M, N)
  benign_filter    = BloomFilter2D(M, N)
  return malicious_filter, benign_filter

malicious_filter, benign_filter = create_filters()

def classify_integrated(features):
    key = vector_to_string(features)

    if malicious_filter.lookup(key):
        return "Malicious", "Malicious Bloom Filter", 1.0

    if benign_filter.lookup(key):
        return "Benign", "Benign Bloom Filter", 1.0

    x = prepare_features_for_cnn(features)
    prob = float(model.predict(x, verbose=0)[0][0])

    if prob >= 0.5:
        malicious_filter.insert(key)
        return "Malicious", "evoCNN", prob
    else:
        benign_filter.insert(key)
        return "Benign", "evoCNN", prob

from sklearn.model_selection import train_test_split

data = pd.read_csv("dataset_preprocessed.csv")

X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values.astype(int)

X_known, X_unseen, y_known, y_unseen = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


for features, label in zip(X_known, y_known):
    key = vector_to_string(features)

    if label == 1:
        malicious_filter.insert(key)
    else:
        benign_filter.insert(key)

print("Known dataset inserted into Bloom filters")
print("Known samples:", len(X_known))
print("Unseen samples:", len(X_unseen))

st.subheader("Upload URL Feature Dataset")

uploaded_file = st.file_uploader(
    "Upload a CSV file containing 79 or 81 URL features",
    type=["csv"]
)

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)

    st.write("Uploaded Data Preview")
    st.dataframe(df.head())

    row_index = st.number_input(
        "Select row index",
        min_value=0,
        max_value=len(df) - 1,
        value=0
    )

    if "label" in df.columns:
        features = df.drop(columns=["label"]).iloc[row_index].values
        actual_label = df["label"].iloc[row_index]
    else:
        features = df.iloc[row_index].values
        actual_label = None

    if st.button("Predict"):
        label, source, confidence = classify_integrated(features)

        st.subheader("Prediction Result")

        if label == "Malicious":
            st.error(f"Prediction: {label}")
        else:
            st.success(f"Prediction: {label}")

        st.write("Source:", source)
        st.write("Confidence:", round(confidence, 4))

        if actual_label is not None:
            st.write("Actual Label:", actual_label)

else:
    st.info("Upload a CSV file to begin prediction.")
